custom: ["https://heliosdev.shop?utm_source=github.com&utm_campaign=github_nonschema_migrations_repo_funding_link",
         "https://shop.heliosdev.shop/?utm_source=github.com&utm_campaign=github_nonschema_migrations_repo_funding_link"]

